preprocessing:
    sample_ratio: 1.0
    sample_size: null
    oversample_minority: null 
    undersample_majority: null
    split:
        type: hash 
        column: sample
        probabilities:
            - 0.7
            - 0.1
            - 0.2

input_features:
  - name: image_path
    type: image
    preprocessing:
      normalization: true
      resize_method: crop_or_pad
      augmentation:
        random_horizontal_flip: true
        random_vertical_flip: true
        random_rotate:
          degree: 15
        random_brightness:
          min: 0.7
          max: 1.3
        random_contrast:
          min: 0.7
          max: 1.3
        random_blur:
          kernel_size: 3
        random_noise: true

    encoder:
      type: resnet 
      use_pretrained: true
      trainable: true
      model_variant: 50 

output_features:
  - name: er_status_by_ihc
    type: binary

trainer:
  epochs: 50
  batch_size: 4 #16
  learning_rate: 0.0001
  optimizer:
    type: adam
  learning_rate_scheduler:
    type: reduce_on_plateau
    metric: accuracy 
    patience: 5
    reduce_rate: 0.5
  validation_field: er_status_by_ihc
  validation_metric: accuracy 
  early_stop: 10
